application: salendron-gcp-demo
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: todo_api.APPLICATION
  secure: always

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
  